---
# DB settings(Have to be the same as the ones in docker-compose)
pg_user: postgres
db_passwd: postgres
pg_name: postgres

# For admin user|not implemented yet
admin_login: admin
admin_ps: possession

# Stuff for main page
side_link: whatever

# Command to activate that shit
# uvicorn app.main:app --reload
